rollout_type: ofa

search_space_type: ofa
search_space_cfg:
  num_cell_groups: [1, 4, 4, 4, 4, 4]
  expansions: [1, 6, 6, 6, 6, 6]
  image_size_choice: [300]
  schedule_cfg:
    kernel_choice:
        type: value
        boundary: [1, 161]
        value: [[7, 5], [7, 5, 3]]
    width_choice:
      type: value
      boundary: [1, 241, 321]
      value: [[6], [6, 4], [6, 4, 3]]
    depth_choice:
      type: value
      boundary: [1, 401, 481]
      value: [[4], [4, 3], [4, 3, 2]]
# ---- End Type mnsanet_ofa ----
## ---- End Component search_space ----

## ---- Component dataset ----
dataset_type: voc
dataset_cfg:
  load_train_only: false
  random_choose: false
  random_seed: 123
  train_crop_size: [300, 300]
  test_crop_size: [300, 300]
  image_mean: 0.
  image_std: 1.
  image_norm_factor: 128.
  image_bias: -1
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component controller ----
# ---- Type rl ----
controller_type: ofa
controller_cfg:
  # Schedulable attributes:
  rollout_type: ofa
# ---- End Type rl ----
## ---- End Component controller ----

## ---- Component evaluator ----
# ---- Type mepa ----
evaluator_type: mepa
evaluator_cfg:
  # Schedulable attributes: controller_surrogate_steps, mepa_surrogate_steps, mepa_samples
  load_optimizer: false
  load_scheduler: false
  rollout_type: ofa
  batch_size: 16
  controller_surrogate_steps: 0
  # derive_surrogate_steps: 0
  mepa_surrogate_steps: 0
  mepa_optimizer:
    lr: 0.05
    momentum: 0.9
    type: SGD
    weight_decay: 0.0001
  mepa_scheduler:
    eta_min: 0.0
    T_0: 80
    type: CosineAnnealingWarmRestarts
  surrogate_optimizer: null
  surrogate_scheduler: null
  mepa_samples: 1
  data_portion:
  - 0.0
  - 0.9 # train evaluator weights
  - 0.1 # for train controller
  mepa_as_surrogate: false
  bptt_steps: 35
  schedule_cfg: null
  workers_per_queue: 8
# ---- End Type mepa ----
## ---- End Component evaluator ----

## ---- Component weights_manager ----
# ---- Type supernet ----
weights_manager_type: wrapper
weights_manager_cfg:
  # Schedulable attributes: 
  rollout_type: ofa
  backbone_type: ofa_supernet
  backbone_cfg:
    backbone_type: mbv3_backbone
    backbone_cfg:
      blocks: [1, 4, 4, 4, 4, 4]
      strides: [1, 2, 2, 2, 1, 2]
      expansions: [1, 6, 6, 6, 6, 6]
      acts: ["relu", "relu", "relu", "h_swish", "h_swish", "h_swish"]
      layer_channels: [16, 16, 24, 40, 80, 112, 160, 960, 1280]
      mult_ratio: 1.
      kernel_sizes: [3, 5, 7]
      block_type: mbv3_block
      pretrained_path: null
  neck_type: ssd
  neck_cfg:
    expansions: [0.5, 0.5, 0.5, 0.5]
  head_type: anchor_based
  head_cfg:
    num_classes: 20
    aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
  feature_levels: [4, 5]
  
# ---- End Type supernet ----
## ---- End Component weights_manager ----

objective_type: detection
objective_cfg:
  # Schedulable attributes:
  num_classes: 20
  anchors_generator_type: ssd_anchors_generator
  anchors_generator_cfg:
    aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
    clip: true
  matcher_type: iou_matcher
  matcher_cfg:
    matched_threshold: 0.5
    unmatched_threshold: 0.4
    variance: [0.1, 0.2]
  loss_type: focal_loss
  loss_cfg:
    alpha: 0.25
    gamma: 2.0
    loc_coef: 1.
  soft_losses_cfg:
    losses_cfg:
      type: adaptive_distillation_loss
      cfg:
        beta: 1.5
        gamma: 1.0
        temperature: 2.
        loss_coef: 0.
        schedule_cfg:
          loss_coef:
            type: value
            boundary: [1, 81]
            value: [0., 0.1]
  post_processing_type: ssd_post_processing
  post_processing_cfg:
    top_k: 200
    confidence_threshold: 0.01
    nms_threshold: 0.5
    variance: [0.1, 0.2]
    apply_prob_type: sigmoid
  metrics_type: voc

final_model_type: wrapper_final_model
final_model_cfg:
  rollout_type: ofa
  genotypes: "image_size=300, cell_0=1,cell_1=4,cell_2=4,cell_3=4,cell_4=4,cell_5=4, cell_0_block_0=(1, 3),cell_1_block_0=(6, 7),cell_1_block_1=(6, 7),cell_1_block_2=(6, 7), cell_1_block_3=(6, 7), cell_2_block_0=(6, 7),cell_2_block_1=(6, 7),cell_2_block_2=(6, 7),cell_2_block_3=(6, 7),cell_3_block_0=(6, 7),cell_3_block_1=(6, 7),cell_3_block_2=(6, 7),cell_3_block_3=(6, 7),cell_4_block_0=(6, 7),cell_4_block_1=(6, 7),cell_4_block_2=(6, 7),cell_4_block_3=(6, 7),cell_5_block_0=(6, 7),cell_5_block_1=(6, 7),cell_5_block_2=(6, 7),cell_5_block_3=(6, 7)"

  supernet_state_dict: null
  backbone_type: ofa_supernet
  backbone_cfg:
      backbone_type: mbv3_backbone
      backbone_cfg:
        layer_channels: [16, 16, 24, 40, 80, 112, 160, 960, 1280]
        strides: [1, 2, 2, 2, 1, 2]
        mult_ratio: 1.
        kernel_sizes: [3, 5, 7]
  neck_type: ssd
  neck_cfg:
    expansions: [0.5, 0.5, 0.5, 0.5]
  head_type: anchor_based
  head_cfg:
    num_classes: 20
    aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
  feature_levels: [4, 5]


final_trainer_type: wrapper_final_trainer
final_trainer_cfg:
  batch_size: 32
  epochs: 30
  optimizer_scheduler:
    eta_min: 0.0
    T_max: 30
    type: CosineAnnealingLR
  schedule_cfg: null
  weight_decay: 0.0001
  learning_rate: 0.005
  warmup_steps: 500
  momentum: 0.9
  save_as_state_dict: true
  eval_every: 10
