controller_cfg:
  rollout_type: germ
  schedule_cfg: null
  perf_names: [reward, FLOPs]
  mutate_kwargs:
    mutate_num: 2
controller_type: pareto-evo
dataset_cfg: {cutout: null}
dataset_type: cifar10
evaluator_cfg:
  batch_size: 256
  bptt_steps: 35
  data_portion: [0.95, [train_testTransform, 0.05]]
  disable_step_current: false
  eval_optimizer: {lr: 0.05, momentum: 0.9, type: SGD, weight_decay: 0.0004}
  eval_samples: 1
  eval_scheduler: {eta_min: 0.0, T_max: 60, type: CosineAnnealingLR}
  evaluate_with_whole_queue: false
  load_optimizer: true
  load_scheduler: true
  rollout_batch_size: 1
  rollout_type: germ
  schedule_cfg: null
  schedule_every_batch: false
  shuffle_data_before_split: false
  shuffle_data_before_split_seed: null
  shuffle_indice_file: null
  strict_load_weights_manager: true
  update_evaluator_report_perfs: true
  workers_per_queue: 2
evaluator_type: discrete_shared_weights
objective_cfg:
    schedule_cfg:
        soft_loss_coeff:
            type: value
            boundary: [1, 61]
            value: [0.0, 6.0]
    soft_loss_coeff: 0.0
objective_type: ofa_classification
rollout_type: germ
search_space_cfg: {} 
search_space_type: germ

trainer_type: async
trainer_cfg:
  # Schedulable attributes: controller_samples, derive_samples
  rollout_type: germ
  steps: 16
  num_epochs: 500
  parallelism: 4
  dispatcher_cfg:
    gpu_ids: [1, 2, 3, 4]
  #trainer_type: simple
  #trainer_cfg: {controller_optimizer: null, controller_samples: 1, controller_scheduler: null,controller_steps: null, controller_train_begin: 500, controller_train_every: 1, derive_samples: 8,epochs: 1000, evaluator_steps: null, interleave_controller_every: null, is_differentiable: false,rollout_batch_size: 1, rollout_type: germ, schedule_cfg: null, test_every: 50}
weights_manager_cfg:
    #germ_def_file: /home/tangchangcheng/projects/aw_nas_private/aw_nas/germ/mbv2.py,
  germ_supernet_type: mbv2 
  germ_supernet_cfg:
        num_classes: 10
        depth_choices: [2, 3, 4]
        strides: [2, 1, 2, 1, 1, 1]
        mult_ratio_choices: [0.5, 0.75, 1.0]
        kernel_sizes: [3, 5, 7]
        expansion_choices: [2, 3, 4, 6]
        stem_stride: 1
        schedule_cfg: {}
  rollout_type: germ
weights_manager_type: germ
