rollout_type: nasbench-101
## ---- Component search_space ----
# ---- Type nasbench-101 ----
search_space_type: nasbench-101-1shot-3
search_space_cfg:
  # Schedulable attributes:
  load_nasbench: true
# ---- End Type nasbench-101 ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar10
dataset_cfg:
  # Schedulable attributes: 
  cutout: null
# ---- End Type cifar10 ----
## ---- End Component dataset ----

## ---- Component controller ----
# ---- Type nasbench-101-sa ----
controller_type: file-sampler 
controller_cfg:
  # Schedulable attributes: 
  rollout_type: nasbench-101
  mode: eval
  archs_path: nb101_14k.yaml
# ---- End Type nasbench-101-sa ----
## ---- End Component controller ----

## ---- Component evaluator ----
# ---- Type nasbench-101 ----
evaluator_type: mepa
evaluator_cfg:
  # Schedulable attributes: controller_surrogate_steps, mepa_surrogate_steps, mepa_samples
  rollout_type: nasbench-101
  batch_size: 256
  mepa_optimizer:
    lr: 0.025
    momentum: 0.9
    type: SGD
    weight_decay: 0.0005
  mepa_scheduler:
    patience: 30
    factor: 0.5
    type: ReduceLROnPlateau
  surrogate_optimizer: null
  surrogate_scheduler: null
  bptt_steps: 35
  mepa_samples: 1
  evaluate_with_whole_queue: false
  data_portion:
  - 0.0
  - 0.8
  - 0.2
  shuffle_data_before_split: false
  shuffle_indice_file: null
  shuffle_data_before_split_seed: null  
  load_optimizer: true
  load_scheduler: true
  controller_surrogate_steps: 0
  mepa_surrogate_steps: 0
  surrogate_optimizer: null
  schedule_every_batch: false
  workers_per_queue: 2
  rollout_batch_size: 1
  
# ---- End Type nasbench-101 ----
## ---- End Component evaluator ----

## ---- Component weights_manager ----
# ---- Type stub ----
weights_manager_type: nasbench-101-official
weights_manager_cfg:
  # Schedulable attributes: 
  rollout_type: nasbench-101
  num_classes: 10
  init_channels: 16
  stem_multiplier: 1
  max_grad_norm: 5.0
  dropout_rate: 0.1
#
# ---- End Type stub ----
## ---- End Component weights_manager ----

## ---- Component objective ----
# ---- Type classification ----
objective_cfg:
  aggregate_as_list: true
  perf_names:
  - grad_norm
  - snip
  - grasp
  - fisher
  - jacob_cov
  - plain
  - synflow_bn
  - synflow
  schedule_cfg: null
objective_type: zero-shot
# ---- End Type classification ----
## ---- End Component objective ----

## ---- Component trainer ----
# ---- Type simple ----
trainer_type: simple
trainer_cfg:
  # Schedulable attributes: controller_samples, derive_samples
  rollout_type: nasbench-101
  is_differentiable: false
  epochs: 1500
  test_every: 2000
  controller_optimizer: null
  controller_scheduler: null
  controller_samples: 1
  derive_samples: 8
  rollout_batch_size: 1
  evaluator_steps: null
  controller_steps: null
  controller_train_every: 1
  controller_train_begin: 2000
  interleave_controller_every: null
  schedule_cfg: null
# ---- End Type simple ----
## ---- End Component trainer ----
